# deploy.yml

name: Build and Deploy to Public Repo

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1: 签出你的私有仓库代码
      - name: Checkout Private Repo
        uses: actions/checkout@v4

      # 步骤 2: 设置 Node.js 环境并安装依赖
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: npm ci

      # 步骤 3: 构建 Eleventy 网站
      - name: Build with Eleventy
        env:
          NODE_ENV: production
        run: npm run build

      # 步骤 4: 将构建好的 _site 文件夹内容推送到你的公开仓库
      - name: Deploy to Public Repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 这是 GitHub Actions 自动生成的一个令牌，让它有权限推送到其他仓库
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # 你的公开部署仓库的名字
          external_repository: austery/austery.github.io
          # 从 _site 文件夹发布
          publish_dir: ./_site
          # 推送到公开仓库的 main 分支
          publish_branch: main
          # 提交信息
          commit_message: ${{ github.event.head_commit.message }}